### ISSUE TITLE
internal misspelling of messenger

### ISSUE THREAD

**Issue by ahicks92** [JuliaAudio/PortAudio.jl#113]
This is one of those things where I am going to be annoying because I haven't broken anything and I assume there's probably a good reason, but if not I'm noticing a lot of misspelling of messenger across the codebase, in the code itself.  I'll come back if I find a way this actually breaks something and I'm new to Julia so perhaps you're running static verifiers I haven't found yet, but it at least seemed like something you might want to know if no one's pointed it out yet.

**Comment by bramtayl** [comment]
Thanks. This should already be fixed on master though? #98

**Comment by ahicks92** [comment]
I was looking at master, I thought.  Possible you missed some?  See: https://github.com/JuliaAudio/PortAudio.jl/blob/master/src/PortAudio.jl#L500

**Comment by bramtayl** [comment]
Ah shoot I did thanks
